#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/qbittorrent              *
*                                                    *
*  https://hub.docker.com/r/linuxserver/qbittorrent  *
*                                                    *
*  https://github.com/linuxserver/docker-qbittorrent *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
